apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  labels:
    name: weaviate
    app: weaviate
    app.kubernetes.io/name: weaviate
    namespace: data-bisgpt-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
        app.kubernetes.io/name: weaviate
    spec:
      volumes:
      - name: "weaviate-data"
        persistentVolumeClaim:
          claimName: "weaviate-data"
      containers:
      - name: weaviate
        image: nexus.bisinfo.org:8099/semitechnologies/weaviate:1.24.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: "/var/lib/weaviate"
            name: "weaviate-data"
        env:
          - name: QUERY_DEFAULTS_LIMIT
            value: '25'
          - name: AUTHENTICATION_APIKEY_ENABLED
            value: 'true'
          - name: AUTHENTICATION_APIKEY_ALLOWED_KEYS
            valueFrom:
              secretKeyRef:
                name: weaviate-keys
                key: keys
          - name: AUTHENTICATION_APIKEY_USERS
            value:  'admin@gpt,user@gpt'
          - name: AUTHORIZATION_ADMINLIST_ENABLED
            value: 'true'
          - name: AUTHORIZATION_ADMINLIST_USERS
            value: 'admin@gpt'
          - name: AUTHORIZATION_ADMINLIST_READONLY_USERS
            value: 'user@gpt'
          - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
            value: 'false'
          - name: PERSISTENCE_DATA_PATH
            value: '/var/lib/weaviate'
          - name: DISABLE_TELEMETRY
            value: 'true'
          - name: DEFAULT_VECTORIZER_MODULE
            value: 'text2vec-openai'
          - name: ENABLE_MODULES
            value: 'text2vec-openai,generative-openai'
          - name: AZURE_APIKEY
            valueFrom:
              secretKeyRef:
                name: weaviate-openai
                key: apiKey
          - name: CLUSTER_HOSTNAME
            value: 'node1'


