kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weaviate-data
  namespace: data-bisgpt-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
